// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Estimate struct {
	ID          int32  `json:"id"`
	ProductName string `json:"product_name"`
	Price       string `json:"price"`
	Longitude   string `json:"longitude"`
	Latitude    string `json:"latitude"`
}
